<?php
session_start();

if (!isset($_COOKIE['cpid']) && !isset($_COOKIE['temp_cpid'])) {
    header('Location: login.php');
    exit;
}

$hostedPaymentOrderId = 'AH-' . strtoupper(bin2hex(random_bytes(8)));
$_SESSION['hostedPaymentOrders'][$hostedPaymentOrderId] = array(
    'amount' => '0.50',
    'createdAt' => time(),
    'status' => 'pending'
);

$hostedPaymentResponse = null;
try {
    include 'getHostedPaymentForm.php';
} catch (Throwable $exception) {
    error_log('Failed to create the PHP Accept Hosted token: ' . $exception->getMessage());
}

$isSuccessful = isset($hostedPaymentResponse)
    && isset($hostedPaymentResponse->messages->resultCode)
    && (string) $hostedPaymentResponse->messages->resultCode === 'Ok';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pay | Accept Sample App</title>
    <link href="scripts/bootstrap.min.css" rel="stylesheet">
</head>
<body style="padding-top: 50px;">
    <main class="container" style="max-width: 720px;">
        <h1>Payment</h1>
        <p><strong>Order reference:</strong> <?php echo htmlspecialchars($hostedPaymentOrderId, ENT_QUOTES, 'UTF-8'); ?></p>

        <div class="panel panel-primary">
            <div class="panel-heading"><h2 class="panel-title">Pay with PHP</h2></div>
            <div class="panel-body">
                <?php if ($isSuccessful): ?>
                    <p>Continue to the secure Authorize.Net hosted payment page using the token generated by PHP.</p>
                    <form action="https://test.authorize.net/payment/payment" method="post">
                        <input type="hidden" name="token" value="<?php echo htmlspecialchars((string) $hostedPaymentResponse->token, ENT_QUOTES, 'UTF-8'); ?>">
                        <button type="submit" class="btn btn-primary btn-lg">Pay (PHP)</button>
                        <a class="btn btn-default btn-lg" href="index.php">Back</a>
                    </form>
                <?php else: ?>
                    <p class="text-danger">Unable to create the PHP token. Please try again.</p>
                <?php endif; ?>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><h2 class="panel-title">Pay with .NET</h2></div>
            <div class="panel-body">
                <p>Request the hosted payment token from the .NET API instead.</p>
                <form action="payWithDotNet.php" method="post">
                    <input type="hidden" name="order" value="<?php echo htmlspecialchars($hostedPaymentOrderId, ENT_QUOTES, 'UTF-8'); ?>">
                    <button type="submit" class="btn btn-success btn-lg">Pay (.NET)</button>
                    <a class="btn btn-default btn-lg" href="index.php">Back</a>
                </form>
            </div>
        </div>
    </main>
</body>
</html>
